name: Build Next js Application
repoFullName: satishp-dev-satishp-dev/circleCI
on:
  push:
    branches:
      - main
jobs:
  run-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.workDir}}
    strategy:
      matrix:
        node-version:
          - 24.0.0
    steps:
      - uses: actions/checkout@v3
        name: Setup jobs
        with:
          fetch-depth: 0
      - name: GitHub Setup
        run: |
          git checkout .
          git checkout main
          git pull origin main
      - uses: actions/setup-node@v3
        name: Setup environment
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install --global yarn 
           yarn
      - name: Building
        run: yarn run build